### ISSUE TITLE
Preparation for publishing on Hackage

### ISSUE THREAD

**Issue by bartavelle** [snoyberg/tar-conduit#1]
I can see this is a fork from @jhance .

@snoyberg : is the original author OK with the publishing ? There is no license in the original repo, and I don't know how much of a rewrite you did.

**Comment by snoyberg** [comment]
The repo itself is a fork. However, if you look at the git history, you'll
see that I authored it all from scratch.

**Comment by bartavelle** [comment]
Perfect!

**Comment by jhance** [comment]
If I mark the repository as private it might remove the assocation, ima try.

**Comment by snoyberg** [comment]
I can also just delete this repo and recreate.

**Comment by snoyberg** [comment]
Seemed to have worked 👍
