### ISSUE TITLE
Simpler APIs

### ISSUE THREAD

**Issue by bartavelle** [snoyberg/tar-conduit#2]
I think there should be a simpler (but more wasteful) API by default before release, something like, that gives a stream of full files:

    tarfiles :: Foo => Conduit ByteString m (Header, ByteString)

What do you think of that ?

**Comment by bartavelle** [comment]
Perhaps even something like:

    tarFiles :: Foo => Conduit ByteString m (FileType, FilePath, ByteString)

Of course, the short bytestring to `String` conversion could be troublesome ...

**Comment by snoyberg** [comment]
I'm not in favor of encouraging an API which is non streaming, it's too
easy to mislead people into writing broken code.

**Comment by bartavelle** [comment]
How is that non-streaming ? I probably wrote broken code then! I though something like that would do the trick:

    withEntries  (\hdr -> CL.consume >>= yield . (hdr,) . mconcat )

It's still streaming, only with bigger chunks, or am I mistaken ? My use case is tarballs containing lots of small files, so this makes a lot of sense to me.

**Comment by snoyberg** [comment]
It's not streaming in the sense that it will use unbounded memory given
large files. You'd be susceptible to an OOM attack if you received a
tarball with large files in it.

**Comment by bartavelle** [comment]
Yes, that is certain. The process that do this have appropriate bounds on the amount of memory they are allowed to consume.

What about just documenting how to do this with the appropriate warnings ? I really believe this is a common use case. Perhaps a function that does truncate large files, with a user supplied size limit, could be helpful ?

**Comment by snoyberg** [comment]
I'd rather document doing things the right way. This really is encouraging
a bad practice.

**Comment by bartavelle** [comment]
Alright!
