### ISSUE TITLE
Publishing on hackage

### ISSUE THREAD

**Issue by bartavelle** [snoyberg/tar-conduit#7]
I added myself as a maintainer in the .cabal file.

The `README` is still empty, but I don't really have time for a long tutorial.

@snoyberg : if both those points are OK to you, I will publish an initial version on hackage and add it in nightly.

**Comment by snoyberg** [comment]
SGTM! 👍

**Comment by bartavelle** [comment]
http://hackage.haskell.org/package/tar-conduit

**Comment by snoyberg** [comment]
Could you add my Hackage account (MichaelSnoyman) as a maintainer in case I need to make uploads in the future?

**Comment by bartavelle** [comment]
That would be sensible, yes. I think I just did it but it doesn't show ... I'll wait a few minutes.

**Comment by bartavelle** [comment]
Its done.

**Comment by snoyberg** [comment]
Thanks!
